### ISSUE TITLE
TypeError: teardown is not a function

### ISSUE THREAD

**Issue by codfish** [knocklabs/knock-client-js#13]
Using the basic usage example in the README.md, I'm getting this error `TypeError: teardown is not a function`.

### Details

- `@knocklabs/client` version: `0.7.1`
- vue app (vue 3)
- The user id I'm passing in the `knockClient.authenticate` call doesn't exist in Knock yet but its not giving me any errors or warnings

It seems to be fetching feed items and logging properly, although we have nothing in there so its just empty, but no connection errors.

**Code:** 

```vue
<script setup>
  import { computed, reactive } from 'vue';
  import { useStore } from 'vuex';
  import Knock from '@knocklabs/client';

  const store = useStore();
  const user = computed(() => store.user);
  const notifications = reactive([]);

  const knockClient = new Knock('*removed*');

  knockClient.authenticate(
    // The id of the user you want to authenticate against
    user.value.id
  );

  const feedClient = knockClient.feeds.initialize('*removed*');

  // Connect to the real-time socket
  const teardown = feedClient.listenForUpdates();

  // Setup a callback for when a batch of items is received (including on first load and subsequent page load)
  feedClient.on('items.received.page', ({ items }) => {
    console.log('items.received.page', items);
    notifications.push(...items);
  });

  // Setup a callback for when new items arrive in real-time
  feedClient.on('items.received.realtime', ({ items }) => {
    console.log('items.received.realtime', items);
    notifications.push(...items);
  });

  // Listen to all received items
  feedClient.on('items.received.*', ({ items }) => {
    console.log('items.received.*', items);
    notifications.push(...items);
  });

  // Fetch the feed items
  feedClient.fetch();

  console.log('teardown', teardown);

  // this is where the error occurs
  teardown(); 
</script>
```

**Here's what I'm getting:**

![image](https://user-images.githubusercontent.com/1666298/184908434-3cc00326-f1a7-4894-94d3-f7eb93d34bf9.png)

**Comment by seanhuggins1** [comment]
Any update on this? `teardown` is simply `void` for me. The example out of the docs does not seem to work.

**Edit:** it appears the example on https://www.npmjs.com/package/@knocklabs/client is a bit dated

`feedClient.teardown()` is the method that works.

**Comment by cjbell** [comment]
Fixed in https://github.com/knocklabs/knock-client-js/commit/f11086c3bfe755f30a92230571746afe394d6895. Thanks both!
