### ISSUE TITLE
Issue with phoenix channel

### ISSUE THREAD

**Issue by elbourki** [knocklabs/knock-client-js#8]
https://github.com/knocklabs/knock-client-js/blob/main/src/clients/feed/feed.ts#L71

The `channelConnected` property isn't set to `true` until the channel receives an `ok` status. But this results in an error (_tried to join multiple times. 'join' can only be called a single time per channel instance_) if the client calls `listenForUpdates` multiple times in succession. I would suggest setting `channelConnected` to `true` right after calling `channel.join()` to prevent this from happening.

**Comment by juanazam** [comment]
@elbourki Thanks for reporting this!

This has been addressed on #9 and it has been effectively released on `0.5.10`

**Comment by elbourki** [comment]
That was fast, thanks a lot @juanazam!
Time to remove my patch-package workaround :D

**Comment by juanazam** [comment]
🙌
